index/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index_view, name='index'),
    path('folium', views.folium_view, name='folium'),
    path('polygon', views.polygon_view, name='polygon'),
    path('grasshopper', views.grasshopper_view, name='grasshopper'),
    path('generation/<int:pk>', views.generation_view, name='generation'),
    path('grass_get', views.grass_get_view, name='grass_get'),
    path('grass_post', views.grass_post_view, name='grass_post'),
    path('dfs', views.dfs_view, name='dfs'),
]

map/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('index.urls')),
    path('adminka/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

index/models.py
from django.db import models


class Generation(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    lat = models.CharField(max_length=10)
    lng = models.CharField(max_length=10)
    polygon = models.TextField()
    radius = models.PositiveSmallIntegerField()
    seats = models.PositiveSmallIntegerField()
    is_generated = models.BooleanField(default=False)
    new_index = models.CharField(max_length=4, null=True, blank=True)
    schools = models.TextField(null=True, blank=True)

    @property
    def idk(self):
        return f"{self.radius}-{self.seats}({self.lat}-{self.lng})"

    def __str__(self):
        return f"[{self.created.strftime('%Y-%m-%d %H:%M:%S')}] {int(self.is_generated)}-{self.idk}"


class Dhp(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    lat = models.CharField(max_length=10)
    lng = models.CharField(max_length=10)
    population = models.PositiveIntegerField()
    adm_zid = models.PositiveSmallIntegerField(db_index=True)

    def __str__(self):
        return f"[{self.created.strftime('%Y-%m-%d %H:%M:%S')}] {self.adm_zid} {self.lat}-{self.lng}"


class Dnd(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=365)
    address = models.CharField(max_length=255)
    year = models.CharField(max_length=16)
    center = models.CharField(max_length=34)
    flats = models.PositiveIntegerField()
    area = models.PositiveIntegerField()
    color = models.CharField(max_length=7)
    adm_zid = models.PositiveSmallIntegerField(db_index=True)

    def __str__(self):
        return f"[{self.created.strftime('%Y-%m-%d %H:%M:%S')}] {self.adm_zid} {self.name}"


class Dsc(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    center = models.CharField(max_length=34)
    students = models.PositiveIntegerField()
    rating = models.PositiveSmallIntegerField()
    color = models.CharField(max_length=7)
    adm_zid = models.PositiveSmallIntegerField(db_index=True)

    def __str__(self):
        return f"[{self.created.strftime('%Y-%m-%d %H:%M:%S')}] {self.adm_zid} {self.name}"


class Ddf(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    adm_name = models.CharField(max_length=64)
    WKT = models.TextField()
    population = models.PositiveIntegerField()
    children = models.PositiveIntegerField()
    students = models.PositiveIntegerField()
    school_k = models.FloatField()
    rating = models.FloatField()
    color = models.CharField(max_length=7)
    adm_zid = models.PositiveSmallIntegerField(db_index=True)

    def __str__(self):
        return f"[{self.created.strftime('%Y-%m-%d %H:%M:%S')}] {self.adm_zid} {self.adm_name}"

index/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.csrf import csrf_exempt

from .models import Generation, Dhp, Dnd, Dsc, Ddf
from .utils import *


def index_view(request):
    adm, okr = request.GET.get('adm', ''), request.GET.get('okr', '')
    ok = list(okr_s.keys())
    ads, is_new = get_ads(okr=okr)
    ad = [adm_s_inv[i] for i in ads] if is_new else list(adm_s.keys())
    if adm not in ad:
        adm = ''
    ads = get_ads(adm, okr)[0]
    df = Ddf.objects.filter(adm_zid__in=ads).values_list('children', 'school_k')
    sc = Dsc.objects.filter(adm_zid__in=ads).count()
    school_k = [i[1] for i in df]
    indicators = [('Количество детей 6-18 лет', sum([i[0] for i in df])),
                  ('Количество школ', sc),
                  ('Средняя обеспеченность', round(sum(school_k) / len(school_k), 2))]
    school_indicator = [len(list(filter(lambda x: x > 1.1, school_k))),
                        len(list(filter(lambda x: 0.9 <= x <= 1.1, school_k))),
                        len(list(filter(lambda x: x < 0.9, school_k)))]
    return render(request, 'index.html', {'adm': adm, 'okr': okr, 'ad': ad, 'ok': ok, 'indicators': indicators,
                                          'school_indicator': school_indicator})


@xframe_options_exempt
def folium_view(request):
    adm, okr = request.GET.get('adm'), request.GET.get('okr')
    ads, is_new = get_ads(adm, okr)
    if is_new:
        return HttpResponse(get_map(ads).get_root().render())
    return render(request, 'folium.html')


def polygon_view(request):
    lat = request.GET.get('lat', '')[:10]
    lng = request.GET.get('lng', '')[:10]
    try:
        if lat and lng:
            res = {'status': True}
            res.update(get_polygon_by_cad(get_cad_by_text(f"{lat}+{lng}", '1')))
            res.update({'isochrone': get_isochrone_polygon(lat, lng)})
            return JsonResponse(res)
    except:
        pass
    return JsonResponse({'status': False})


def grasshopper_view(request):
    try:
        radius = int(request.GET.get('radius', ''))
    except:
        radius = ''
    try:
        seats = int(request.GET.get('seats', ''))
    except:
        seats = ''
    lat = request.GET.get('lat', '')[:10]
    lng = request.GET.get('lng', '')[:10]
    if not(lat and lng and radius and seats):
        return JsonResponse({'status': False})
    polygon = get_polygon_by_cad(get_cad_by_text(f"{lat}+{lng}", '1'))['polygon']
    gen = Generation(lat=lat, lng=lng, polygon=polygon, radius=radius, seats=seats)
    gen.save()
    return JsonResponse({'status': True, 'n': gen.pk})


def generation_view(_, pk):
    gen = Generation.objects.filter(pk=pk).first()
    if not(gen and gen.is_generated):
        return JsonResponse({'status': False})
    res = {'new_index': gen.new_index, 'grasshopper_img': f"/static/gens/{gen.pk}.jpg",
           'objects': json.loads(gen.schools), 'status': True}
    return JsonResponse(res)


@csrf_exempt
def grass_get_view(request):
    if request.method != 'POST' or request.POST.get('mine_key') != MINE_TOKEN:
        return JsonResponse({'status': False})
    gen = Generation.objects.filter(is_generated=False).first()
    if gen is None:
        return JsonResponse({'status': False})

    data = {'idk': gen.pk, 'lat': gen.lat, 'lng': gen.lng, 'polygon': gen.polygon,
            'radius': gen.radius, 'seats': gen.seats, 'bbox': get_bbox_osm(gen.lat, gen.lng, 800)}
    return JsonResponse({'status': True, **data})


@csrf_exempt
def grass_post_view(request):
    if request.method != 'POST' or request.POST.get('mine_key') != MINE_TOKEN:
        return JsonResponse({'status': False})
    gen = Generation.objects.filter(pk=int(request.POST.get('idk'))).first()
    if gen is None:
        return JsonResponse({'status': False})

    save_base64_to_file(request.POST.get('image'), f"{STATIC_ROOT}/gens/{gen.pk}.jpg")
    gen.new_index = round(float(request.POST.get('new_index')), 2)
    gen.schools = request.POST.get('schools')
    gen.is_generated = True
    gen.save()
    return JsonResponse({'status': True})


@login_required
@user_passes_test(lambda user: user.is_superuser)
def dfs_view(request):
    if request.method != 'POST':
        return JsonResponse({'status': False})
    for i, cls in enumerate([Dhp, Dnd, Dsc, Ddf], 1):
        cls.objects.all().delete()
        df = pd.read_csv(request.FILES[f"d{i}.csv"]).drop(columns={'Unnamed: 0'})
        bulk_create_iter(cls, df)
    m = get_map(get_ads()[0])
    m.save(str(BASE_DIR) + '/templates/folium.html')
    return JsonResponse({'status': True})

templates/index.html
<!DOCTYPE html>
{% load static %}
{% load filters %}
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title>SREDA – образование</title>
	<link rel="shortcut icon" href="{% static 'img/icon.png' %}">
	<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=1">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div id="BOX">

	<img id="LOGO" src="{% static 'img/logo.png' %}" title="Команда проекта SREDA разработала настоящий сайт и гордится этим"
		 onclick="$('#MAP').removeClass('hidden'); $('#SCREEN').addClass('hidden');
		 $('#INFO-1').removeClass('hidden'); $('#INFO-2').addClass('hidden'); if (cad) { cad.remove(); } if (iso) { iso.remove(); }">

	<div id="MAP"><iframe src="{% url 'folium' %}?adm={{ adm }}&okr={{ okr }}" frameborder="0" width="100%" height="100%"></iframe></div>

	<div id="SCREEN" class="hidden"><img id="SCREEN__map" src="/static/img/1.jpg"></div>

	<div id="INFO-1">
		<div id="INFO-1__top">
			<div><span id="mayor_of_moscow">Конкурсное решение <br>на соискание премий<br> Мэра Москвы</span></div>
			<div><a href="https://leaders2021.innoagency.ru" target="blank_"><img src="{% static 'img/lct_logo.png' %}"></a></div>
		</div>

		<form action="" method="GET">
			<div class="m_title">Выберите округ и район</div>
			{% include "items/filter.html" with title='Округ' idk='okr' lst=ok val=okr %}
			{% include "items/filter.html" with title='Район' idk='adm' lst=ad val=adm %}
		</form>
		<div class="indicators">
			<div class="m_title">Метрики</div>
			{% for title, value in indicators %}
			<div class="indicator">
				<div class="title">{{ title }}</div>
				<div class="value">{{ value|to_price }}</div>
			</div>
			{% endfor %}
		</div>
		<div class="school_indicator">
			<div class="m_title">Типы районов</div>
			<div class="table">
				<div class="row">
					<div class="cell"><div class="val">{{ school_indicator.0 }}</div><div class="text">районов</div></div>
					<div class="cell"><div class="val">Профицит</div><div class="text">Индекс более 1,1</div></div>
				</div>
				<div class="row">
					<div class="cell"><div class="val">{{ school_indicator.1 }}</div><div class="text">районов</div></div>
					<div class="cell"><div class="val">Норма</div><div class="text">Индекс от 0.9 до 1,1</div></div>
				</div>
				<div class="row">
					<div class="cell"><div class="val">{{ school_indicator.2 }}</div><div class="text">районов</div></div>
					<div class="cell"><div class="val">Дефицит</div><div class="text">Индекс менее 0.9</div></div>
				</div>
			</div>
		</div>

		<div id="INFO-1__bottom">
			<div><span><a href="https://sreda.expert" target="blank_">Связаться с авторами</a></span></div>
			<div>
				<a href="https://sreda.expert" target="blank_"><img src="{% static 'img/sreda_logo.png' %}"></a>
				<a href="https://trend-hunter.ru/" target="blank_"><img src="{% static 'img/trend_hunter_logo.webp' %}"></a>
				<a href="https://www.mgpu.ru/" target="blank_"><img src="{% static 'img/mgpu_logo.svg' %}"></a>
			</div>
		</div>
	</div>

	<div id="INFO-2" class="hidden">
		<div id="INFO-2__radius" class="form_field">
			<input id="radius__range" type="range" min="300" max="1500" step="1" name="radius" class="my_select_slider" value="500">
			<div class="my_values"><div>300</div><div>1500</div><div class="text_value"><span class="value">500</span> </div></div>
			<label for="radius__range" class="form_label">Радиус, м</label>
		</div>

		<div id="INFO-2__places" class="form_field">
			<input id="places__range" type="range" min="100" max="1500" step="1" name="places" class="my_select_slider" value="300">
			<div class="my_values"><div>100</div><div>1500</div><div class="text_value"><span class="value">300</span> </div></div>
			<label for="places__range" class="form_label">Мест в новой школе</label>
		</div>

		<div id="INFO-2__generate">
			<input id="id_lat" type="hidden" name="lat">
			<input id="id_lng" type="hidden" name="lng">
			<button id="generate" onclick="grasshopper()"><p>Генерация</p></button>
		</div>

		<div id="INFO-2__index" class="hidden">
			<p>Индекс в новой школе</p>
			<div class="small-serif">
				<p class="new_index">0.95</p>
			</div>
		</div>

		<div id="INFO-2__objects" class="hidden">
			<p>Объекты</p>
			<div id="INFO-2__objects__objects" class="small-serif"></div>
			<div id="object_template" class="object" style="display: none;">
				<div><p class="object__name"></p></div>
				<div><p class="object__address"></p></div>
				<div><p>Корпусов</p><p class="object__buildings"></p></div>
				<div><p>Учащихся</p><p class="object__customers"></p></div>
				<div>
					<p>Индекс текущий</p>
					<div><p class="object__index_current"></p></div>
				</div>
				<div>
					<p>Индекс прогноз</p>
					<div><p class="object__index_predict"></p></div>
				</div>
			</div>
		</div>
	</div>

</div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/script.js' %}"></script>
<script>
    iframe = $('iframe')[0].contentWindow; var cad; var iso;
    function map_click(e) {
        console.log(e.latlng.lat, e.latlng.lng);
        if (map.getZoom() >= 14) {
            $.ajax({ url: '{% url "polygon" %}', data: {lat: e.latlng.lat, lng: e.latlng.lng}, success: function(data){
                console.log(data.status); if (cad) { cad.remove(); } if (iso) { iso.remove(); }
                if (data.status) {
                	cad = iframe.L.polygon($.parseJSON(data.polygon), {color: '#ec0e4c'}).addTo(map);
                	iso = iframe.L.geoJSON(data.isochrone, {color: '#110932'}).addTo(map);
                	$('#INFO-1, #INFO-2__index, #INFO-2__objects').addClass('hidden'); $('#INFO-2').removeClass('hidden');
                	$('#INFO-2__objects__objects').empty();
                	$('#id_lat').val(e.latlng.lat); $('#id_lng').val(e.latlng.lng);
               	}
            }});
        }
    }
    function get_generation(n) {
		$.ajax({ url: '/generation/'+n, success: function(data){
			if (data.status) {
				$('#MAP').addClass('hidden'); $('#SCREEN, #INFO-2__index, #INFO-2__objects').removeClass('hidden');
				$('#INFO-2__objects__objects').empty();
				for (let i = 0; i < data.objects.length; i++) {
					temp = $("#object_template").clone(); temp.removeAttr('id'); temp.removeAttr('style');
					for (prop in data.objects[i]) { temp.find('.object__'+prop).text(data.objects[i][prop]); }
					$('#INFO-2__objects__objects').append(temp);
				}
				$('.new_index').text(data.new_index); $('#SCREEN__map').attr("src", data.grasshopper_img);
				$('#generate').prop( "disabled", false );
			} else { setTimeout(() => get_generation(n), 1000); }
		}});
	}
    function grasshopper() {
    	lat = $('#id_lat').val(); lng = $('#id_lng').val();
		$.ajax({ url: '/grasshopper?lat='+$('#id_lat').val()+'&lng='+$('#id_lng').val()+'&radius='+$('#radius__range').val()+'&seats='+$('#places__range').val(), success: function(data){
			if (data.status) { get_generation(data.n); $('#generate').prop( "disabled", true ); }
		}});
	}
    (async() => {
        while(!(iframe.$ && iframe.$('.folium-map')))
            await new Promise(resolve => setTimeout(resolve, 1000));
        map_id = iframe.$('.folium-map').attr('id');
        while(!(iframe[map_id] && iframe[map_id].on))
            await new Promise(resolve => setTimeout(resolve, 1000));
        map = iframe[map_id]; map.on('click', map_click);
    })();
</script>
<script src='https://cdn.experrto.io/client/experrto.js'></script>
<script>Experrto.identify("fce4463c7a3026f2fc725addc3d377da46900ae2");</script>
</html>

templates/items/filter.html
{% load static %}

<div id="{{ idk }}_div" class="filter_div">
	<button onclick="$(this).toggleClass('show');" class="filter_btn" type="button">
		<span class="title{% if val %} hidden{% endif %}">{{ title }}</span>
		<span class="val">{% if val %}{{ val }}{% endif %}</span>
		<img src="{% static 'img/expand.svg' %}" alt="">
	</button>
	<div class="filter_list">
		<input type="hidden" id="id_{{ idk }}" name="{{ idk }}" value="{{ val }}" class="filter_hidden">
		<input type="text" placeholder="Поиск..." id="{{ idk }}" class="filter_input">
		{% if val %}<a class="clear"><img src="{% static 'img/close.svg' %}" alt="Очистить"></a>{% endif %}
		{% for txt in lst %}<a{% if txt == val %} class="selected"{% endif %}>{{ txt }}</a>{% endfor %}
	</div>
</div>